### ISSUE TITLE
Can't open .tic file

### ISSUE THREAD

**Issue by darltrash** [flathub/com.tic80.TIC_80#3]
It seems like tic80 crashes or something before being able to actually access the file, and drag-and-drop does not work either

![imagen](https://user-images.githubusercontent.com/38925212/174670738-b140400f-8a20-4e5e-a76e-6bfd4241f25f.png)

![imagen](https://user-images.githubusercontent.com/38925212/174671230-9be00f05-f5ce-4c95-9df5-a33304e9b42b.png)

I am currently running latest Fedora, Gnome 42

**Comment by kevinsmia1939** [comment]
Could you try to install flatseal from flathub and enable --filesystem=home and see if it work?

**Comment by darltrash** [comment]
> Could you try to install flatseal from flathub and enable --filesystem=home and see if it work?

Used `sudo flatpak override com.tic80.TIC_80 --filesystem=home` and...
![imagen](https://user-images.githubusercontent.com/38925212/174672523-3dd9cc4f-17d2-4e41-888a-05822cb2650b.png)

Sadly, Drag-and-drop doesn't work yet, and as far as i know it should use portals instead of straight up allowing access to `~`, hopefully TIC-80 gets portals support, probably diving into the code to implement it myself later (even though i do not know much about it lol)

**Comment by kevinsmia1939** [comment]
hmm, filesystem=home fix drag and drop for me.

**Comment by darltrash** [comment]
> hmm, filesystem=home fix drag and drop for me.

Pretty strange, to be honest
Maybe it's a SDL2 wayland thing?

**Comment by darltrash** [comment]
Yup, can confirm, works flawlessly on X11
Guess I'll have to wait until the next version of the freedesktop runtime

**Comment by kevinsmia1939** [comment]
This PR hopefully fix this. Reopen of not.
https://github.com/flathub/com.tic80.TIC_80/pull/7
