### ISSUE TITLE
Sandbox settings: allow permissions for gamepads

### ISSUE THREAD

**Issue by Liorst4** [flathub/com.tic80.TIC_80#5]
Installed it on my steamdeck.
The app didn't register the game controller.

Workaround: Used flatseal to allow TIC-80 access to all devices.

If there is a more granular way to allow access only to input devices, you should use it instead,

**Comment by kevinsmia1939** [comment]
I'm not aware if there is the option to allow only the game controller. If not, then access to all device is the only choice.
